version: '3'

services:
  mini-cdn:
    image: node:20
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"