version: '3'

services:
  node-app:
    image: node:16
    working_dir: /usr/src/app
    command: sh -c "npm install && node index.js"
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"